-- ================================================
-- Proactive Nudges Schema
-- Logic: Persistent notifications generated by AI or system
-- ================================================

CREATE TABLE IF NOT EXISTS nudges (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES users(id) ON DELETE CASCADE,
    type VARCHAR(50) NOT NULL, -- e.g., 'claim_reminder', 'leave_balance', 'birthday', 'system'
    title VARCHAR(255) NOT NULL,
    content TEXT NOT NULL,
    metadata JSONB DEFAULT '{}'::jsonb, -- e.g., { "claim_id": "..." }
    is_read BOOLEAN DEFAULT false,
    sent_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Index for unread nudges per user
CREATE INDEX IF NOT EXISTS idx_nudges_user_unread ON nudges(user_id, is_read) WHERE is_read = false;

-- Trigger updated_at
CREATE TRIGGER nudges_updated_at BEFORE UPDATE ON nudges
    FOR EACH ROW EXECUTE FUNCTION update_updated_at();
